@baseUrl = http://taskoverflow-401638518.us-east-1.elb.amazonaws.com

@task_id = ceeb2468-038e-4137-b1ee-0a970d798097

### Health
GET {{baseUrl}}/api/v1/health

### create async cal gen job
POST {{baseUrl}}/api/v1/todos/ical 
Accept: application/json

### get status of generation job
GET {{baseUrl}}/api/v1/todos/ical/{{task_id}}/status 
Accept: application/json

### get result of generation job
GET {{baseUrl}}/api/v1/todos/ical/{{task_id}}/result 
Accept: application/json